
# Adam PC
#FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04 

# 5TONIC server
FROM nvidia/cuda:12.0.0-devel-ubuntu22.04

LABEL maintainer="azahir@pa.uc3m.es"

# Set bash as default shell, and avoid prompts during package installation
SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      cudnn9-cuda-12 `# pulls in libcudnn.so.9 & the Graph API libs` \
      python3 \
      python3-dev \
      python3-pip \
      python3-setuptools \
      git wget \ 
      pkg-config libsleef-dev \
      libcurl4-openssl-dev \
      file patchelf && \
    rm -rf /var/lib/apt/lists/*

COPY app/ /app/

# Create a working directory
WORKDIR /app


RUN wget -q https://s3.nbfc.io/nbfc-assets/github/vaccel/rev/main/x86_64/debug/vaccel_latest_amd64.deb && \
	apt install ./vaccel_latest_amd64.deb && rm vaccel_latest_amd64.deb && \
	wget -q https://s3.nbfc.io/nbfc-assets/github/vaccel/rust/rev/main/x86_64/release/vaccel-rpc-agent_latest_amd64.deb && \
	apt install ./vaccel-rpc-agent_latest_amd64.deb && rm ./vaccel-rpc-agent_latest_amd64.deb && \
	wget -q https://s3.nbfc.io/nbfc-assets/github/vaccel/plugins/rpc/rev/main/x86_64/release/vaccel-rpc_latest_amd64.deb && \
	apt install ./vaccel-rpc_latest_amd64.deb && rm vaccel-rpc_latest_amd64.deb

COPY requirements.txt /tmp/requirements.txt

RUN pip3 install pip --upgrade && pip3 install -r /tmp/requirements.txt

RUN cp models/monocular_deployed_gpu/sol_monocular.py models/monocular_deployed_gpu/sol_monocular_example.py

RUN apt install -y 

RUN cd models/monocular_deployed_vaccel && bash -x prepare.sh

ENV VACCEL_PLUGINS=libvaccel-exec.so
ENV VACCEL_LOG_LEVEL=1
ENV VACCEL_EXEC_DLOPEN_MODE=lazy
ENV VACCEL_EXEC_DLCLOSE_ENABLED=0
ENTRYPOINT ["vaccel-rpc-agent", "-a", "tcp://0.0.0.0:8192"]

